### ISSUE TITLE
Crash on publishing/viewing blog post

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#382] opened 2019-02-10 11:12 UTC
Ran into this while trying to do something else...
NoDB site created from template with this option: "blog only with blog as default route". Run from VS, login in as admin.

Create blog post (default html) and publish >>>

InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'cloudscribe.SimpleContent.Web.ViewModels.BlogViewModel', but this ViewDataDictionary instance requires a model item of type 'cloudscribe.SimpleContent.Models.ProjectSettings'.
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(object value)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, object model, Type declaredModelType)
lambda_method(Closure , ViewDataDictionary )
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorPagePropertyActivator.CreateViewDataDictionary(ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorPagePropertyActivator.Activate(object page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, object model)
Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
AspNetCore.Views_Blog_Post.ExecuteAsync()

**Comment by joeaudette** [comment] 2019-02-10 13:59
I was not able to produce the problem,

I think maybe you missed a critical step, after you create the project you should always right click the project, choose Manage NuGet Packages and update all of the cloudscribe packages to the latest version. 
This is indicated in the readme that opens after creating the project in VS.

**Comment by joeaudette** [comment] 2019-02-10 14:13
Closing this since I could not reproduce it, if the problem persists after updating the nugets feel free to re-open.

**Closed by joeaudette** 2019-02-10 14:13 UTC

**Comment by joeaudette** [comment] 2019-02-14 12:12
fyi, got a separate bug report on this with steps to reproduce it. It happened only if you check the show blog title and description in content settings. It is fixed now in the latest view nuget.

**Comment by CrispinF** [comment] 2019-02-14 12:29
Great, thanks Joe.
