### ISSUE TITLE
A page scheduled to publish in future is not publishing at the designated time (5 hour offset)

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#316] opened 2018-07-26 15:16 UTC
Testing the "Publish Later" functionality, I set a page to publish at a given time, and it didn't.
![image](https://user-images.githubusercontent.com/10574730/43270309-aa571126-90ec-11e8-80d5-becf6befcfae.png)

And in another browser, at 15:58, we still get Page Not Found.

OK I think there's a regional settings issue. The site Time Zone by default was in America/New York. Switching this to "GB", with no change to the above page, made it show this:
![image](https://user-images.githubusercontent.com/10574730/43270636-7a416b70-90ed-11e8-90be-ce06106e1414.png)
Back into the editor, I changed the publish time to this:
![image](https://user-images.githubusercontent.com/10574730/43270762-c432f69a-90ed-11e8-988c-c65714798eea.png)
but on loading the page it showed this:
![image](https://user-images.githubusercontent.com/10574730/43270793-d476d53a-90ed-11e8-9381-2944d7c8c59e.png)

I thought there might be a caching issue after changing the site Time Zone, but after restarting I see exactly the same.  On saving the publication time, it is offset +5 hours from what I set in the editor. If I set it to current time minus 5 hours, the page becomes published.
My machine regional settings are default UK.

Small possibly related issue: even with my machine and browser in UK settings, the date in the "Publish Later" control shows in US date format "07/26/2018 4:15 PM"  (I'd expect "26/07/2018 4:15 PM").

**Comment by joeaudette** [comment] 2018-07-26 18:49
@CrispinF in order for UK culture to work, you need to add it as a supported culture in Config/Localization.cs, only en-US is added by default in the project template.

**Comment by joeaudette** [comment] 2018-07-26 18:54
scheduled publishing seems to work for me when you hit the url after the scheduled time.

However, I do think there is an issue I had not thought through. If you schedule a page or post for future publishing it will only ever get published if the url is visited. But the url won't be visited by a user who does not know it exists. Without some kind of task to come along and publish content that is due to be published it won't appear in the menu or post list.

So we may need to make the page index action look for any unpublished page that is due for publishing and publish it instead of just looking at the page for the current url. Similarly we probably need to make the blog index action do the same for unpublished posts.

**Comment by CrispinF** [comment] 2018-07-26 20:40
@joeaudette regarding culture, I thought that was only for "forced culture" i.e. overriding browser, no? My machine and browsers claim to be already in UK settings.

Agree about menu and blog index - needs to pick up the newly published items.

**Comment by CrispinF** [comment] 2018-07-27 07:34
@joeaudette just coming back to this, are you definitely saying the publication time offset was because I don't have GB localisation in place? (I thought that only affected presentation / forced UI culture).  Puzzled why it's not using the Time Zone setting?
(My issue was deinifeitly not caused by the menu issue that you described above, as I was visiting the URL directly).

**Comment by joeaudette** [comment] 2018-07-27 12:45
@CrispinF there are couple of different things going on here.

In ASP.NET Core localization is different than older ASP.NET, you have to explicitly declare your supported cultures. The forced culture feature of cloudscribe can only force a supported culture, the dropdown list there only shows the supported cultures. If you create a standard asp.net core web app without specifying any supported cultures then it will only support en-US as far as I know and will not be localized. The cloudscribe template stubs out code to declare your supported cultures but only en-US is uncommented in keeping with the default behavior of asp.net core. I will go ahead and uncomment en-GB next time I publish a template update since I hear cloudscribe is getting popular in the UK  :-D 
Browsers pass a header indicating the preferred culture but it will not be used unless it is also a supported culture. So to get the datepicker to format en-GB you would need to uncomment that line in /Config/Localization.cs to make en-GB a supported culture.

But that is not the cause of the issue. SimpleContent was developed independently of cloudscribe Core and it always has had the time zone controlled by the "project" time zone not by a user time zone and that is the problem. If the user time zone in cloudscribe core is different than the site timezone (which corresponds to project time zone) then what happens is the user posts a time based on his own time zone but on postback it is treated as if it is the project timezone. In all cases the display of dates uses the project time zone, but it is problem for the editor not using the user time zone to convert to UTC and that is what needs to be fixed and this issue wasn't introduced by recent work. In the meantime it should work correctly if edit user time zone matches the site time zone.

**Comment by CrispinF** [comment] 2018-07-27 14:06
@joeaudette OK I see that once I have enabled en-GB in localisation.cs the UI gives me UK date formats.

Regarding publication dates, I can get a variety of offsets, depending what Site Settings Time Zone I choose. I've tried setting the time zone of my account to GB and the site time zone to GB also, which I think you suggested should work(?), and I still get the 5 hour offset. Should I wait for a fix?

**Comment by joeaudette** [comment] 2018-07-27 19:54
in the latest nugets the user timezone is used and I am pretty sure that will solve the problem.
Also now publishing drafts will happen for any draft that is due to be published so that the new menu item will appear for pages and the new post will appear for the blog list

**Comment by joeaudette** [comment] 2018-08-07 16:43
@CrispinF are you satisfied with this one? can we close it?

**Comment by joeaudette** [comment] 2018-08-09 12:02
closing this, feel free to re-open if you are still having any issue

**Closed by joeaudette** 2018-08-09 12:02 UTC
